# Generated by Django 5.2.5 on 2025-09-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
